name: Trigger email
on:
  workflow_dispatch:
#  schedule:
#    # Runs https://crontab.guru/#0_18_*_*_*
#    - cron: '*/30 * * * *'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl -vL https://steffenmllr-rimowa.deno.dev
